### ISSUE TITLE
Install error: "TypeError: 'encoding' is an invalid keyword argument for this function"

### ISSUE THREAD

**Issue by QEDeD** [aadibajpai/SwagLyrics-For-Spotify#381]
When attemping to install I get the following result:

> pip install swaglyrics
> Collecting swaglyrics
>   Using cached https://files.pythonhosted.org/packages/47/c1/1247500905d767137f5cf9b8e084e017bd2d2978e151bfd0327dc7cdcde1/swaglyrics-0.2.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-am80iD/swaglyrics/setup.py", line 3, in <module>
>         with open("README.md", "r", encoding='utf8') as fh:
>     TypeError: 'encoding' is an invalid keyword argument for this function

pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

**Comment by T1duS** [comment]
Try python3 -m pip install swaglyrics

**Comment by QEDeD** [comment]
Thanks for the quick response, tried without sudo which didn't work, but 

> sudo python3 -m pip install swaglyrics

 worked.

**Comment by aadibajpai** [comment]
Right. I'll add Linux instructions too. Thanks for making the issue!

**Comment by QEDeD** [comment]
> Thanks for using! Feel free to suggest more improvements!

It would be nice with clearer seperation between songs, when lyrics are displayed via -c it can be hard to tell at a gance when lyrics for one song stops and another begin.

**Comment by aadibajpai** [comment]
The command line is supposed to clear when lyrics update. Is that not what happens?

**Comment by QEDeD** [comment]
No, that doesn't seem to be the case for me (screenshot): https://i.imgur.com/FGzt6t9.png

**Comment by aadibajpai** [comment]
@QEDeD I see it says cls command not found. So, this has been fixed already in the repo but wasn't included in the compiled pip package that I uploaded. Don't worry, it'll be fixed in the next release.

**Comment by aadibajpai** [comment]
Heads up, should be fixed

**Comment by QEDeD** [comment]
Thanks :+1: I've updated to .23 
It seems to be working better, but if I understand your intention only the current songs lyrics should be displayed? Currently, it seems to show the lyrics for both the current and last song with the current lyrics displayed at the top: https://i.imgur.com/9ITD24h.png

**Comment by aadibajpai** [comment]
The image isn't very clear, can you post a clearer one? Can't see your console.

**Comment by QEDeD** [comment]
How is this? https://i.imgur.com/8AdZKPC.png
The resolution should be quite high (1280 × 1396)

**Comment by aadibajpai** [comment]
Cool, will be fixed in the next release. Thanks for letting me know!
