### ISSUE TITLE
Weird Dream by I Hate Sex unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#434]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> I-Hate-Sex-Weird-Dream</b></tt>

**Comment by T1duS** [comment]
https://genius.com/I-hate-sex-weird-dream-conscious-stream-lyrics
