### ISSUE TITLE
I Hate Sports by I Hate Sex unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#435]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> I-Hate-Sex-I-Hate-Sports</b></tt>

**Comment by T1duS** [comment]
https://genius.com/I-hate-sex-i-fucking-hate-sports-lyrics
