### ISSUE TITLE
[BUG ]Extra issues being created when running unit tests

### ISSUE THREAD

**Issue by T1duS** [aadibajpai/SwagLyrics-For-Spotify#45]
Extra Issues are created when unit tests are run. See here for example --
https://github.com/aadibajpai/SwagLyrics-For-Spotify/issues?q=is%3Aissue+is%3Aclosed
Most issues don't make any sense.

**Comment by T1duS** [comment]
I mean in the unit tests, if we call get_lyrics({random},{random})  extra issues will be created as unsupported songs while actually the song doesn't exist

**Comment by aadibajpai** [comment]
Technically that's how it's supposed to work but I get your point about not wanting to create an actual issue while testing

**Comment by aadibajpai** [comment]
closed by https://github.com/aadibajpai/SwagLyrics-For-Spotify/commit/acf95c24b097ea848db25c0a4d8cd0181c9c6302
