### ISSUE TITLE
As Long As You Love Me (feat. Emelie Cyréus) by Chad Cooper unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#450]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Chad-Cooper-As-Long-As-You-Love-Me</b></tt>

**Comment by T1duS** [comment]
https://genius.com/Chad-cooper-and-robaer-as-long-as-you-love-me-lyrics
