### ISSUE TITLE
E-Lo (feat. Jozzy) by Los Unidades unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#634]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Los-Unidades-E-Lo</b></tt>

**Comment by T1duS** [comment]
https://genius.com/Los-unidades-and-pharrell-williams-e-lo-lyrics
