### ISSUE TITLE
Ella Quiere Beber - Remix by Anuel Aa unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#636]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Anuel-Aa-Ella-Quiere-Beber</b></tt>

**Comment by T1duS** [comment]
https://genius.com/Anuel-aa-ella-quiere-beber-remix-lyrics
