### ISSUE TITLE
Girl from the North Country (Cover) by Passenger unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#637]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Passenger-Girl-from-the-North-Country</b></tt>

**Comment by T1duS** [comment]
https://genius.com/Passenger-girl-from-the-north-country-cover-lyrics
