### ISSUE TITLE
Couldn't get lyrics 

### ISSUE THREAD

**Issue by addddd123** [aadibajpai/SwagLyrics-For-Spotify#732]
Couldn't get lyrics for Kar Gayi Chull by Badshah.
That's a fishy request, that artist and song doesn't seem to exist on Spotify.

**Comment by aadibajpai** [comment]
Weird, I get the message that Lyrics Unavailable. Could you walk me through what you did?

**Comment by addddd123** [comment]
I was playing Indian song so it displayed
"something fishy couldn't get lyrics....."

**Comment by aadibajpai** [comment]
Can you play that same song again and show a screenshot?

**Comment by addddd123** [comment]
Wait bro

I send u screen short either here or on slack

**Comment by aadibajpai** [comment]
Looks like it works correctly

**Comment by addddd123** [comment]
check this out fishy request......
