### ISSUE TITLE
Potato Salad by Tyler, The Creator unsupported.

### ISSUE THREAD

**Issue by aadibajpai** [aadibajpai/SwagLyrics-For-Spotify#796]
Check if issue with swaglyrics or whether song lyrics unavailable on Genius. 
<hr>
 <tt><b>stripper -> Tyler-The-Creator-Potato-Salad</b></tt>

**Comment by sakshambassi** [comment]
The song lyrics are available on Genius (https://genius.com/Tyler-the-creator-and-a-ap-rocky-potato-salad-lyrics)
Can you help me out in finding the issue?

**Comment by aadibajpai** [comment]
added support

**Comment by aadibajpai** [comment]
@sakshambassi yeah, the stripper did not match `Tyler-the-creator-and-a-ap-rocky-potato-salad` so it wasn't able to fetch lyrics.

SwagLyrics gets only the first artist from song so it did not get A$AP Rocky in this song.

**Comment by sakshambassi** [comment]
Oh, understood.
